name: Astrobotany

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install packages
      run: |
        pip install .
        pip install .[test]
    - name: Lint with mypy
      run: |
        mypy --ignore-missing-imports .
    - name: Run tests
      run: |
        pytest -v tests/
